export const REGISTER_REQUEST="REGISTER_REQUEST"
export const REGISTER_SUCCESS="REGISTER_REQUEST"
export const REGISTER_FAILURE="REGISTER_FAILURE"


export const LOGIN_REQUEST="LOGIN_REQUEST"
export const LOGIN_SUCCESS="LOGIN_SUCCESS"
export const LOGIN_FAILURE="LOGIN_FAILURE"

export const LOGOUT="LOGOUT"

export const LOGIN_TWO_STEP_REQUEST="LOGIN_TWO_STEP_REQUEST"
export const LOGIN_TWO_STEP_SUCCESS="LOGIN_TWO_STEP_SUCCESS"
export const LOGIN_TWO_STEP_FAILURE="LOGIN_TWO_STEP_FAILURE"


export const GET_USER_REQUEST="GET_USER_REQUEST"
export const GET_USER_SUCCESS="GET_USER_SUCCESS"
export const GET_USER_FAILURE="GET_USER_FAILURE"




export const SEND_VERFICATION_OTP_REQUEST="SEND_VERFICATION_OTP_REQUEST"
export const SEND_VERFICATION_OTP_SUCCESS="SEND_VERFICATION_OTP_SUCCESS"
export const SEND_VERFICATION_OTP_FAILURE="SEND_VERFICATION_OTP_FAILURE"



export const ENABLE_TWO_STEP_AUTHENTICATION_REQUEST="ENABLE_TWO_STEP_AUTHENTICATION_REQUEST"
export const ENABLE_TWO_STEP_AUTHENTICATION_SUCCESS="ENABLE_TWO_STEP_AUTHENTICATION_SUCCESS"
export const ENABLE_TWO_STEP_AUTHENTICATION_FAILURE="ENABLE_TWO_STEP_AUTHENTICATION_FAILURE"


export const VERIFY_OTP_REQUEST="VERIFY_OTP_REQUEST"
export const VERIFY_OTP_SUCCESS="VERIFY_OTP_SUCCESS"
export const VERIFY_OTP_FAILURE="VERIFY_OTP_FAILURE"


export const SEND_RESET_PASSWORD_REQUEST="SEND_RESET_PASSWORD_REQUEST"
export const SEND_RESET_PASSWORD_SUCCESS="SEND_RESET_PASSWORD_SUCCESS"
export const SEND_RESET_PASSWORD_FAILURE="SEND_RESET_PASSWORD_FAILURE"




export const VERIFY_RESET_PASSWORD_REQUEST="VERIFY_RESET_PASSWORD_REQUEST"
export const VERIFY_RESET_PASSWORD_SUCCESS="VERIFY_RESET_PASSWORD_SUCCESS"
export const VERIFY_RESET_PASSWORD_FAILURE="VERIFY_RESET_PASSWORD_FAILURE"



export const FETCH_COIN_LIST_REQUEST="FETCH_COIN_LIST_REQUEST"
export const FETCH_COIN_LIST_SUCCESS="FETCH_COIN_LIST_SUCCESS"
export const FETCH_COIN_LIST_FAILURE="FETCH_COIN_LIST_FAILURE"


export const FETCH_TOP_50_COIN_REQUEST="FETCH_TOP_50_COIN_REQUEST"
export const FETCH_TOP_50_COIN_SUCCESS="FETCH_TOP_50_COIN_SUCCESS"
export const FETCH_TOP_50_COIN_FAILURE="FETCH_TOP_50_COIN_FAILURE"



export const FETCH_MARKET_CHART_REQUEST="FETCH_MARKET_CHART_REQUEST"
export const FETCH_MARKET_CHART_SUCCESS="FETCH_MARKET_CHART_SUCCESS"
export const FETCH_MARKET_CHART_FAILURE="FETCH_MARKET_CHART_FAILURE"



export const FETCH_COIN_BY_ID_REQUEST="FETCH_COIN_BY_ID_REQUEST"
export const FETCH_COIN_BY_ID_SUCCESS="FETCH_COIN_BY_ID_SUCCESS"
export const FETCH_COIN_BY_ID_FAILURE="FETCH_COIN_BY_ID_FAILURE"


export const FETCH_COIN_DETAILS_REQUEST="FETCH_COIN_DETAILS_REQUEST"
export const FETCH_COIN_DETAILS_SUCCESS="FETCH_COIN_DETAILS_SUCCESS"
export const FETCH_COIN_DETAILS_FAILURE="FETCH_COIN_DETAILS_FAILURE"



export const SEARCH_COIN_REQUEST="SEARCH_COIN_REQUEST"
export const SEARCH_COIN_SUCCESS="SEARCH_COIN_SUCCESS"
export const SEARCH_COIN_FAILURE="SEARCH_COIN_FAILURE"


